### ISSUE TITLE
魅蓝note3机型上会出现动画显示不完全的情况

### ISSUE THREAD

**Issue by cyjthink** [Hanccc/ProgressDialog#2]
![issues](http://7xvlun.com1.z0.glb.clouddn.com/issue_1.png)

**Comment by Hanson** [comment]
图挂了 - -

**Comment by cyjthink** [comment]
重新上传了

**Comment by Hanson** [comment]
确定资源全部都在？而且从图可以看出动画并没有在toast的正中间

**Comment by cyjthink** [comment]
资源都在，其他机型上没问题，就魅蓝note3上有问题

**Comment by Hanson** [comment]
这个可能要麻烦你自己解决了，我已经3年没开发android了

本人解决思路：
先取消动画，查看全部资源正常情况下显示是否正常，进行调整

从图上看的感觉是，资源的大小问题导致的，估计是有动画在转动只是没有显示全部而已

**Comment by cyjthink** [comment]
十分感谢
